purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.1875
  lightness: 0.75
  brandColors:
    - '#1E313F'
    - '#2C72B0'
    - '#5B95C5'
    - '#94C1D8'
    - '#D8E4E0'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: lifestylecalgary
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4426523
layout_spectrum: 0.2939068
