name: lifestylecalgary
favicon: null
layout_spectrum: 0.74811
typography_spectrum: 0.48834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f454f'
    - '#c2b6a4'
    - '#5f7178'
    - '#dbdee0'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
