name: lifestylecalgary
favicon: null
layout_spectrum: 0.6146183172240853
typography_spectrum: 0.5789243108592927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06886306731030345
  lightness: 0.7576315191108733
  saturation: 0.07692623836919665
  rhythmicContrast: 0.06803801120258868
purpose: []
